### ISSUE TITLE
It works on macOS 11

### ISSUE THREAD

**Issue by alphara** [tml1024/FluffyDisplay#1]
I just launched the FluffyDisplay on macOS 11.2 Big Sur. Thanks for creating such application. It helps me with 2 MacBooks Pro. I am creating a virtual display with FluffyDisplay on the first mac and connect from the second mac over VNC.

**Comment by tml1024** [comment]
Thanks! Good that it is useful. I haven't really worked on it (or even used it) much lately, but once I get the inspiration again I will start using it more myself and do some further improvements.

**Comment by tml1024** [comment]
(I guess there is no reason to keep this issue open as such then.)

**Comment by alphara** [comment]
Sure. Just wanted to say thanks.

**Comment by Ajibaji** [comment]
just used the same method to connect an older macbook (2008). thanks!
