### ISSUE TITLE
"New on peer" - What is the usage of this function?

### ISSUE THREAD

**Issue by mmm117** [tml1024/FluffyDisplay#12]
Hi, thanks for this excellent project. 

I have a simple question, I did read the project description and try the "New on peer" function, but it just created a new virtual screen which has the same resolution as another Mac running on my network, nothing more, is the "New on peer" function supposed to work like this?  I don't understand... thanks. 

============================

You can also run FluffyDisplay also on the other Mac. In that case the main Mac notices that and automatically adds a menu "New on peer" (suggestions for better but still short name welcome) under which will appear the displays of other Macs running FluffyDisplay. When you choose one of those, FluffyDisplay on that other Mac will automatically start ScreenSharing to connect to your main Mac.

**Comment by tml1024** [comment]
Sorry, I don't really remember any more, and I don't actually use FluffyDisplay myself any more. The old iMac became so unreliable I couldn't use it any more even just as a "remote display" through FluffyDisplay.

**Comment by mmm117** [comment]
Hi, even you see the description below, you still can't remember it?  So I think the development should be stopped, right?
Thanks. 

--------
You can also run FluffyDisplay also on the other Mac. In that case the main Mac notices that and automatically adds a menu "New on peer" (suggestions for better but still short name welcome) under which will appear the displays of other Macs running FluffyDisplay. When you choose one of those, FluffyDisplay on that other Mac will automatically start ScreenSharing to connect to your main Mac.

**Comment by mmm117** [comment]
> Sorry, I don't really remember any more, and I don't actually use FluffyDisplay myself any more. The old iMac became so unreliable I couldn't use it any more even just as a "remote display" through FluffyDisplay.

Hi, even you see the description below, you still can't remember it? So I think the development should be stopped, right?
Thanks.

You can also run FluffyDisplay also on the other Mac. In that case the main Mac notices that and automatically adds a menu "New on peer" (suggestions for better but still short name welcome) under which will appear the displays of other Macs running FluffyDisplay. When you choose one of those, FluffyDisplay on that other Mac will automatically start ScreenSharing to connect to your main Mac.

**Comment by tml1024** [comment]
OK, good that you found the documentation for it.

Feel free to consider the development stopped.

**Comment by mmm117** [comment]
> OK, good that you found the documentation for it.
> 
> Feel free to consider the development stopped.

But I don't understand this function even after I read the documentation for it :-)
