### ISSUE TITLE
Custom resolution requires

### ISSUE THREAD

**Issue by F-Unction** [tml1024/FluffyDisplay#2]
I use iPad as a display, but there isn't correct resolution.
I would appreciate it if you make it support define resolution by myself or you add it(2388*1668) to the preset resolution.
Thank you very much.

**Comment by F-Unction** [comment]
Hello?

**Comment by F-Unction** [comment]
I have requested to merge my branch of more solutions.
But I think custom resolutions is also necessary.

**Comment by tml1024** [comment]
Ah, Hackintosh. Sorry, I have no interest in supporting people who don't respect copyright. The whole Open Source concept is based on copyright.
