### ISSUE TITLE
How do you "Start FluffyDisplay"

### ISSUE THREAD

**Issue by theadw** [tml1024/FluffyDisplay#4]
Not an issue but not sure where to ask - How do you "Start FluffyDisplay"? Each time i open, opens it in textEdit.

**Comment by sushantnadkar** [comment]
> Not an issue but not sure where to ask - How do you "Start FluffyDisplay"? Each time i open, opens it in textEdit.

+1

**Comment by tml1024** [comment]
So how do you attempt to start it?

Download the .zip file, let Safari unpack it (or unpack it manually), and you get FluffyDisplay.app. You run that. Works for me.

**Comment by S0ULB0Y** [comment]
still cant open it safari just downloads the file and leaves the file as it is. It doesn't become .app file. Could you put the .app file on github cause I tried building it in xcode to get the .app file but it returns this "Showing Recent Messages No signing certificate "Developer ID Application" found: No "Developer ID Application" signing certificate matching team ID "DD8CRV ROU7" with a private key was found. "

**Comment by sushantnadkar** [comment]
**DO NOT** download the code base in ZIP format from the `Code` dropdown on the project home page (as I did), as shown below:
![Screenshot 2021-10-03 at 08 35 31](https://user-images.githubusercontent.com/8912289/135746421-1bd0f070-5ae3-45bc-9cce-1ccc087e7aab.png)


Instead, download form _Releases_ page, by clicking on _Releases_ > _Assets_ > _FluffyDisplay-1.0.5.zip_, as shown below:
![Screenshot 2021-10-03 at 08 37 09](https://user-images.githubusercontent.com/8912289/135746426-ac4939c2-154a-46e2-b8ff-b1e9fc24693b.png)

![Screenshot 2021-10-03 at 08 35 52](https://user-images.githubusercontent.com/8912289/135746423-2f313a3d-fffd-4e00-9a66-b36356fc4587.png)

**Comment by mmm117** [comment]
> So how do you attempt to start it?
> 
> Download the .zip file, let Safari unpack it (or unpack it manually), and you get FluffyDisplay.app. You run that. Works for me.

Do you know will it work on M1 silicon mac?
Thanks for the great project!!

**Comment by psomhorst** [comment]
> > So how do you attempt to start it?
> > Download the .zip file, let Safari unpack it (or unpack it manually), and you get FluffyDisplay.app. You run that. Works for me.
> 
> Do you know will it work on M1 silicon mac? Thanks for the great project!!

I'm currently running it on an M1 MacBook Pro. Works as advertised!

**Comment by tml1024** [comment]
This has been answered now, closing.
